# Generated by Django 2.2.2 on 2019-07-02 04:37

from django.db import migrations, models
import django.utils.timezone
import wishItems.models

# python3 manage.py makemigrations
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WishItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('wantness', models.IntegerField()),
                ('price', models.IntegerField(validators=[wishItems.models.validate_price])),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('result', models.CharField(max_length=255, verbose_name='result')),
            ],
        ),
    ]
