# Generated by Django 2.2.2 on 2019-07-02 04:37

from django.db import migrations
from django.utils import timezone
import datetime

# python3 manage.py makemigrations --empty --name wishItems wishItems
# python3 manage.py migrate
def create_wish_item(apps, schema_editor):
    wishItem = apps.get_model('wishItems', 'wishItem')
    wishItem(name="Dyson V8", wantness=7, price=589, result="Pending").save()
    wishItem = apps.get_model('wishItems', 'wishItem')
    wishItem(name="Mario Tennis", wantness=3, price=79.99, result="Pending").save()

class Migration(migrations.Migration):

    dependencies = [
        ('wishItems', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_wish_item),
    ]
