# Generated by Django 2.2.2 on 2019-10-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishItems', '0003_wishitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishitem',
            name='img_url',
            field=models.CharField(default=' ', max_length=255, verbose_name='img_url'),
            preserve_default=False,
        ),
    ]
